name: Fedora 42 Images
on:
  merge_group:
  workflow_call:
  workflow_dispatch:

jobs:
  build-image-42:
    name: Build Fedora 42 Images
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    strategy:
      fail-fast: false
    with:
      image_flavors: '["main", "nvidia-open"]'
      brand_name: '["cosmic", "cosmic-dx"]'
      fedora_version: 42

  # generate-release:
  #   name: Generate Release
  #   needs: [build-image-latest]
  #   secrets: inherit
  #   uses: ./.github/workflows/generate-release.yml
  #   with:
  #     stream_name: '["latest"]'

  # build-iso-latest:
  #   name: Build Latest ISOs
  #   needs: [build-image-latest]
  #   if: github.event.schedule == '50 4 * * 0'
  #   secrets: inherit
  #   uses: ./.github/workflows/build-iso-latest.yml
